name: Run BookMyShow Scraper

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (adjust as you like)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper

      - name: Run scraper
        run: |
          python main.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.json
          git commit -m "Auto-update movies & venues data [skip ci]" || echo "No changes to commit"
          git push
